CREATE USER PROKANADM IDENTIFIED BY think;
-- Grant DBA role
GRANT DBA TO PROKANADM;
-- Grant unlimited tablespace
GRANT UNLIMITED TABLESPACE TO PROKANADM;

CREATE TABLE PROKANADM.USERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL
);

CREATE TABLE PROKANADM.TASKS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    COMPLETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES PROKANADM.USERS(ID) ON DELETE CASCADE
);



GRANT SELECT, INSERT, UPDATE, DELETE ON PROKANADM.USERS TO PROKANADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROKANADM.TASKS TO PROKANADM;
